---
name: Tests

on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - "cmd/**"
      - "internal/**"
      - "main.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

jobs:
  tests:
    name: Go Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Run tests
        run: go test ./...
